function output_txt = hover_branch(obj, i_branch)

    str_tag   = char(obj.str_branch(i_branch));
    str_class = replace(char(obj.tab_branch{i_branch,"class"}),'_','\_');
    
    rv_I = abs(obj.cm_Ibranch(:,i_branch));
    rv_P = obj.rm_Pbranch(:,i_branch);
    rv_Q = obj.rm_Qbranch(:,i_branch);
    
    Ploss    = sum(rv_P);
    Qstore   = sum(rv_Q);
    r_Vargij = -diff(angle(obj.cm_Vbranch(:,i_branch))) /pi*180;

    iv_edge = obj.im_edge(:,i_branch);

    output_txt = {['\fontname{SansSerif}\bf{',str_tag,' @', str_class,'}'] , ...   
                  ['\fontname{SansSerif}\bf{ on Branch}']  , ...
                  ['\fontname{Monospaced} {\it ∠V_{ij}}  = ' , num2str(r_Vargij),'^\circ']  , ...
                  ['\fontname{Monospaced} {\it P}_{loss } = ', num2str(Ploss)]          , ...
                  ['\fontname{Monospaced} {\it Q}_{store} = ', num2str(Qstore)]         , ...
                  ' '                                      , ...
                  ['\fontname{SansSerif}\bf{ From Side(Bus',num2str(iv_edge(1)),')-->Branch}']  , ...
                  ['\fontname{Monospaced} {\it |I|} = ', num2str(rv_I(1))]  , ...
                  ['\fontname{Monospaced} {\it P} = ',   num2str(rv_P(1))]  , ...
                  ['\fontname{Monospaced} {\it Q} = ',   num2str(rv_Q(1))]  , ...
                  ' '                             , ...
                  ['\fontname{SansSerif}\bf{ To Side(Bus',num2str(iv_edge(2)),')-->Branch}']  , ...
                  ['\fontname{Monospaced} {\it |I|} = ', num2str(rv_I(2))]  , ...
                  ['\fontname{Monospaced} {\it P} = ',   num2str(rv_P(2))]  , ...
                  ['\fontname{Monospaced} {\it Q} = ',   num2str(rv_Q(2))]    ...
                  };
end