function [node, edge] = get_geometric_parts( obj, rm_X, rm_U, cr_Vbus, cr_Ibus, rr_Pbus, rr_Qbus)
    delta  = rm_X(1,:);
    rr_Pm  = rm_U(1,:);
    rr_Vfd = rm_U(2,:);

    dij = angle(cr_Vbus) - delta;
    Vd  = abs(cr_Vbus) .* sin(dij);

    data = [ rr_Vfd; rr_Vfd+1j*Vd] .* [1;1]*exp(1j*delta);

    node(1) = struct('Color', [0,0,0,1],...
                     'Label', [] ,...
                     'Hover', [] , ...
                     'Pset' , nan, ...
                     'Qset' , nan, ...
                     'Pflow', nan, ...
                     'Iflow', nan, ...
                     'Varg' , angle(data(2,:)), ...
                     'Vabs' , abs(data(2,:)) );
    
    node(2) = struct('Color',[1,0,0,1]        ,...
                     'Label','Gen'            ,...
                     'Hover', obj.get_tag + "("+tab_PFset.Type+")", ...
                     'Pset' , rr_Pm           , ...
                     'Qset' , nan             , ...
                     'Pflow', rr_Pbus         , ...
                     'Iflow', rr_Qbus./Eq     , ...
                     'Varg' , angle(data(1,:)), ...
                     'Vabs' , abs(data(1,:)) );
    edge = [1;2];
end