function val = check_CostFunction(obj,func)
    V = tools.complex2vec(obj.V_equilibrium);
    I = tools.complex2vec(obj.I_equilibrium);
    try
        val = func(obj,0,V,I);
    catch
        error(['The function handle seems to be in the wrong format.',newline,...
               'It must be in the following format',newline,...
               'func = @(obj,t,V,I) ~',newline,...
               '・obj : own class object',newline,...
               '・t = time(scalar)',newline,...
               '・V = [real(V);imag(V)]',newline,...
               '・I = [real(I);imag(I)]',newline])
    end
end