(function (root) {
  const data = {
  "schema": {
    "name": "GUILDA class document",
    "version": 2
  },
  "ClassName": "odeEventSet",
  "properties": [
    {
      "Name": "str_tag",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": true,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "TimeSpan",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "OffsetUnit",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "OffsetState",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "OffsetValue",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "FaultBus",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "TripUnit",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "InputUnit",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "InputName",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "InputValue",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "odeNetwork",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "odeTimeSpan",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "odeIteration",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "sv_Btag",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "sv_Ctag",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "rv_Brep",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "rv_Crep",
      "Defining": "odeEventSet",
      "GetAccess": "private",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Ver",
      "Defining": "odeEventSet",
      "GetAccess": "public",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": true,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    }
  ],
  "methods": [
    {
      "Name": "odeEventSet",
      "Defining": "odeEventSet",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Event2State",
      "Defining": "odeEventSet",
      "Access": "odeSimulator",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "getInitialCondition",
      "Defining": "odeEventSet",
      "Access": "odeSimulator",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "setEventCondition",
      "Defining": "odeEventSet",
      "Access": "odeSimulator",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "table",
      "Defining": "odeEventSet",
      "Access": "odeSimulator",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "getTimeSpan",
      "Defining": "odeEventSet",
      "Access": "private",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "mustBeVector",
      "Defining": "odeEventSet",
      "Access": "private",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "validateTimeSpanSize",
      "Defining": "odeEventSet",
      "Access": "private",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    }
  ],
  "validation": {
    "Warnings": [
      "odeEventSet: class has no Summary or Desc.",
      "odeEventSet.odeEventSet: public method has no Summary or Desc."
    ],
    "Errors": []
  }
};
  root.GUILDA_DOC_CLASSES = root.GUILDA_DOC_CLASSES || {};
  root.GUILDA_DOC_CLASSES["odeEventSet"] = data;
  root.classData = data;
})(window);
