const classData = {
  "ClassName": "PowerSystem",
  "properties": [
    {
      "Name": "tab_parameter",
      "Defining": "LayerPackage",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": true,
      "Constant": false,
      "Abstract": true,
      "Hidden": false,
      "Desc": "manage parameter related to any analyis.",
      "Role": "Parameter",
      "Type": "Parameter",
      "Size": "1x1"
    },
    {
      "Name": "parent",
      "Defining": "LayerPackage",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": true,
      "Constant": false,
      "Abstract": true,
      "Hidden": false,
      "Desc": "manage hierarchical structure of layers.",
      "Role": "Layer Structure",
      "Type": "LayerPackage",
      "Size": "1x1"
    },
    {
      "Name": "children",
      "Defining": "LayerPackage",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": true,
      "Constant": false,
      "Abstract": true,
      "Hidden": false,
      "Desc": "manage hierarchical structure of layers.",
      "Role": "Layer Structure",
      "Type": "LayerPackage cell array",
      "Size": "Nx1"
    },
    {
      "Name": "str_editFlag",
      "Defining": "LayerPackage",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "Flag to indicate if the layer has been edited.",
      "Role": "Edit Log",
      "Type": "string",
      "Size": "1x1"
    },
    {
      "Name": "tab_editLog",
      "Defining": "LayerPackage",
      "GetAccess": "public",
      "SetAccess": "private",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "Log of edits made to the layer, including timestamp, ID, log message, tag, and before/after states.",
      "Role": "Edit Log",
      "Type": "table",
      "Size": "Nx6"
    },
    {
      "Name": "l_managedTag",
      "Defining": "LayerPackage",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "Flag to indicate if the layer is managed by the tag system.",
      "Role": "Tag",
      "Type": "logical",
      "Size": "1x1"
    },
    {
      "Name": "str_tag",
      "Defining": "LayerPackage",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "User-defined tag for the layer, used for identification and management within the layer structure.",
      "Role": "Tag",
      "Type": "string",
      "Size": "1x1"
    }
  ],
  "methods": [
    {
      "Name": "PowerSystem",
      "Defining": "PowerSystem",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "The PowerSystem class serves as a base class for classes that constitute the power system model.\nIt is designed to separate classes that make up the power system model from those intended for analysis assistance.\n- Classes that constitute the power system model >> Inherit from PowerSystem\n- Classes intended for analysis assistance >> Inherit from auxiliary",
      "Role": "Class Category",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "disp_tree",
      "Defining": "LayerPackage",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "check_edit",
      "Defining": "LayerPackage",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "reset_edit",
      "Defining": "LayerPackage",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "log_edit",
      "Defining": "LayerPackage",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "attach_tag",
      "Defining": "LayerPackage",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "get_tag",
      "Defining": "LayerPackage",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Desc": "",
      "Role": "",
      "Abst": "",
      "Argin": "",
      "Argout": "",
      "Option": ""
    },
    {
      "Name": "string",
      "Defining": "LayerPackage",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": true,
      "Desc": "when string() method is called on the object, it returns the tag string for data transformation.\n>> str = string(obj)",
      "Role": "Tag",
      "Abst": "convert the object to a string representation",
      "Argin": "None",
      "Argout": "str - The string representation of the object, typically derived from the tag.",
      "Option": "None"
    },
    {
      "Name": "table",
      "Defining": "LayerPackage",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": true,
      "Desc": "when table() method is called on the object, it returns the parameter table for data transformation.\n>> tab = table(obj)",
      "Role": "Parameter",
      "Abst": "convert the object's parameters into a table format for data transformation purposes.",
      "Argin": "None",
      "Argout": "tab - The parameter table.",
      "Option": "None"
    }
  ]
};
