(function (root) {
  const data = {
  "schema": {
    "name": "GUILDA class document",
    "version": 2
  },
  "ClassName": "tools.for_graph.map",
  "properties": [
    {
      "Name": "a_bus",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "a_component",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "a_branch",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "a_busline",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Graph",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Quiver",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "ColorMap",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Colorbar",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "ZLim",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": true,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "XLim",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": true,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "YLim",
      "Defining": "tools.for_graph.map",
      "GetAccess": "public",
      "SetAccess": "public",
      "Dependent": true,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "G",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Axes",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "net",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "nbus",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "nbr",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Edge_idx_branch",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Edge_idx_BusLine",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "Edge_idx_nonunit",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "normalize_range",
      "Defining": "tools.for_graph.map",
      "GetAccess": "protected",
      "SetAccess": "protected",
      "Dependent": false,
      "Constant": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Type": "",
      "Size": "",
      "Unit": "",
      "Default": "",
      "Constraints": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    }
  ],
  "methods": [
    {
      "Name": "val2color",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "normalize",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "adapt_GraphCoordinate",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "set_Color_subject2CompType",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "set_Color_subject2BusType",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "remove_margin",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "initialize",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "build_graph",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "map",
      "Defining": "tools.for_graph.map",
      "Access": "public",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "format_VI",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "format_xu",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "refresh_quiver",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "set_quiver",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "plot_circle",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    },
    {
      "Name": "set_colorbar",
      "Defining": "tools.for_graph.map",
      "Access": "protected",
      "Static": false,
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Signatures": [],
      "Parameters": [],
      "Returns": [],
      "Examples": [],
      "Notes": "",
      "Throws": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": ""
    }
  ],
  "validation": {
    "Warnings": [
      "tools.for_graph.map: class has no Summary or Desc.",
      "tools.for_graph.map.val2color: public method has no Summary or Desc.",
      "tools.for_graph.map.normalize: public method has no Summary or Desc.",
      "tools.for_graph.map.adapt_GraphCoordinate: public method has no Summary or Desc.",
      "tools.for_graph.map.set_Color_subject2CompType: public method has no Summary or Desc.",
      "tools.for_graph.map.set_Color_subject2BusType: public method has no Summary or Desc.",
      "tools.for_graph.map.remove_margin: public method has no Summary or Desc.",
      "tools.for_graph.map.initialize: public method has no Summary or Desc.",
      "tools.for_graph.map.build_graph: public method has no Summary or Desc.",
      "tools.for_graph.map.map: public method has no Summary or Desc."
    ],
    "Errors": []
  }
};
  root.GUILDA_DOC_CLASSES = root.GUILDA_DOC_CLASSES || {};
  root.GUILDA_DOC_CLASSES["tools.for_graph.map"] = data;
  root.classData = data;
})(window);
