function val = check_CostFunction(obj,func)
    x = obj.x_equilibrium;
    u = obj.u_equilibrium;
    V = obj.V_equilibrium;
    I = obj.I_equilibrium;
    try
        val = func(obj,0,x,V,I,u);
    catch
        error(['The function handle seems to be in the wrong format.',newline,...
               'It must be in the following format',newline,...
               'func = @(obj,t,x,V,I,u) ~',newline,...
               '・obj : own class object',newline,...
               '・t = time(scalar)',newline,...
               '・x = state vector',newline,...
               '・V = [real(V);imag(V)]',newline,...
               '・I = [real(I);imag(I)]',newline,...
               '・u = input vector',newline])
    end
end