function text = struct2text(data)
    fn = fieldnames(data);
    text = tools.hcellfun(@(field) ['\textbf{',cut(field),'}\newline',...
                              newline,...
                              tools.make_tex_data.table2tex(data.(field)),...
                              '\newline',...
                              newline],fn);
end

function str = cut(str)
    str(str=='_') = ' ';
end