const class_list = [
  {
    "Name": "LayerPackage",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "handle",
    "Abstract": true,
    "Hidden": false,
    "Desc": "Abstract base class for layer hierarchy management in GUILDA.\nIt centralizes parent/children relationships, tag handling, and edit logging.",
    "Role": "auxiliary",
    "Constructor": "This class is abstract and should not be instantiated directly.\n\nLayerPackage のドキュメンテーション\ndoc LayerPackage",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/LayerPackage.js"
  },
  {
    "Name": "PowerSystemModel",
    "Type": "other",
    "Model": "",
    "Parent": "LayerPackage",
    "Abstract": true,
    "Hidden": false,
    "Desc": "The PowerSystemModel class serves as a base class for classes that constitute the power system model.\nIt is designed to separate classes that make up the power system model from those intended for analysis assistance.\n- Classes that constitute the power system model >> Inherit from PowerSystemModel\n- Classes intended for analysis assistance >> Inherit from auxiliary",
    "Role": "Class Category",
    "Constructor": "None\n\nPowerSystemModel のドキュメンテーション\ndoc PowerSystemModel",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/PowerSystemModel.js"
  },
  {
    "Name": "auxiliary",
    "Type": "other",
    "Model": "",
    "Parent": "LayerPackage",
    "Abstract": true,
    "Hidden": false,
    "Desc": "The auxiliary class serves as a base class for classes that are intended for analysis assistance.\nIt is designed to separate classes that make up the power system model from those intended for analysis assistance.\n- Classes that constitute the power system model >> Inherit from PowerSystemModel\n- Classes intended for analysis assistance >> Inherit from auxiliary",
    "Role": "Class Category",
    "Constructor": "None\n\nauxiliary のドキュメンテーション\ndoc auxiliary",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/auxiliary.js"
  },
  {
    "Name": "Branch",
    "Type": "PowerSystemModel",
    "Model": "Branch",
    "Parent": "PowerSystemModel",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/Branch.js"
  },
  {
    "Name": "Bus",
    "Type": "PowerSystemModel",
    "Model": "Bus",
    "Parent": "PowerSystemModel",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/Bus.js"
  },
  {
    "Name": "Component",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "PowerSystemModel",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/Component.js"
  },
  {
    "Name": "Cubicle",
    "Type": "PowerSystemModel",
    "Model": "Cubicle",
    "Parent": "PowerSystemModel",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/Cubicle.js"
  },
  {
    "Name": "GlobalController",
    "Type": "PowerSystemModel",
    "Model": "GlobalController",
    "Parent": "PowerSystemModel",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/GlobalController.js"
  },
  {
    "Name": "LocalController",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "PowerSystemModel",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/LocalController.js"
  },
  {
    "Name": "PowerNetwork",
    "Type": "PowerSystemModel",
    "Model": "PowerNetwork",
    "Parent": "PowerSystemModel",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/PowerNetwork.js"
  },
  {
    "Name": "ControllerPackage",
    "Type": "PowerSystemModel",
    "Model": "",
    "Parent": "PowerSystemModel",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/ControllerPackage.js"
  },
  {
    "Name": "tools.for_graph.map",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map.js"
  },
  {
    "Name": "tools.for_graph.plot",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.plot.js"
  },
  {
    "Name": "tools.FigureClass",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.FigureClass.js"
  },
  {
    "Name": "tools.ProgressReporter",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.ProgressReporter.js"
  },
  {
    "Name": "DaeFactory",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/DaeFactory.js"
  },
  {
    "Name": "GraphMassSpring",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary",
    "Abstract": true,
    "Hidden": false,
    "Desc": "This class implements a mass-spring system for graph visualization, designed to be used within the GUILDA software.\n\nYou can instantiate a GraphMassSpring object with specified parameters for nodes, edges, and visual properties.\n>> gms = GraphMassSpring(numNodes, edges, opt);\n\nIf you want to build a mass-spring system with PowerNetwork class information, use the \"import_PowerNetwork\" method.\n>> gms = GraphMassSpring();\n>> gms.import_PowerNetwork(powerNetworkObj, opt);",
    "Role": "Graph Visualization",
    "Constructor": ">> GraphMassSpring(numNodes, edges, opt)\nConstructs a GraphMassSpring object with specified parameters.\n- numNodes: Number of nodes in the graph (default: 2)\n- edges: An Nx2 array specifying the edges between nodes (default: [1,2])\n- opt: A struct of optional parameters, including:\n- nodeRadius: Radius of the nodes (default: 0.08)\n- nodeColors: An Nx4 array specifying RGBA colors for each node (default: green with full opacity)\n- springWidth: A 1xM array specifying the width of each spring (default: 0.015 for all springs)\n- springStyle: A 1xM array specifying the style of each spring (default: 0 for all springs)\n- contourLevels: A 1xK array specifying contour levels for visualization (default: 0.2:0.2:1.4)\n- timeInterval: Time interval for updates (default: 1/60 seconds)\n- nodeRadii: A 1xN array specifying individual radii for each node (default: 0.08 for all nodes)\n- nodeTexts: A 1xN string array specifying text labels for each node (default: \"1\", \"2\", ..., \"N\")\n- hoverNodeTexts: A 1xN string array specifying hover text for each node (default: \"Node1\", \"Node2\", ..., \"NodeN\")\n- hoverEdgeTexts: A 1xM string array specifying hover text for each edge (default: \"Edge1\", \"Edge2\", ..., \"EdgeM\")\n\nGraphMassSpring のドキュメンテーション\ndoc GraphMassSpring",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/GraphMassSpring.js"
  },
  {
    "Name": "Parameter",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "auxiliary, dynamicprops",
    "Abstract": false,
    "Hidden": false,
    "Desc": "The Parameter class is designed to manage parameters related to PowerSystemModel. \nIt serves as a structured way to handle parameters, including their values, changes, and associated callbacks. \nIf any parameter is changed, the class automatically triggers a callback function, triggering LayerPackage's log_edit function, which logs the edit and updates the edit flag.",
    "Role": "Edit Log, Parameter",
    "Constructor": ">> Parameter(a_parent, str_tag, CallBackChanged)\nThe constructor initializes the Parameter object with a reference to its parent layer (a_parent), a user-defined tag (str_tag), and a callback function (CallBackChanged) that is executed when a parameter change is detected. The tag is used for identification and management within the layer structure, while the callback function allows for custom behavior to be defined in response to parameter changes.\n\nParameter のドキュメンテーション\nhelpwin Parameter\n\nParameter のその他の使用\n\nSimulink.SimulationData/Parameter",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/Parameter.js"
  },
  {
    "Name": "branch.T",
    "Type": "PowerSystemModel",
    "Model": "Branch",
    "Parent": "Branch",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/branch.T.js"
  },
  {
    "Name": "branch.pi",
    "Type": "PowerSystemModel",
    "Model": "Branch",
    "Parent": "Branch",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/branch.pi.js"
  },
  {
    "Name": "branch.pi_transformer",
    "Type": "PowerSystemModel",
    "Model": "Branch",
    "Parent": "Branch",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/branch.pi_transformer.js"
  },
  {
    "Name": "branch.two_winding_transformer",
    "Type": "PowerSystemModel",
    "Model": "Branch",
    "Parent": "Branch",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/branch.two_winding_transformer.js"
  },
  {
    "Name": "component.GFM.Inverter",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.Inverter.js"
  },
  {
    "Name": "component.farm.solar",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.farm.solar.js"
  },
  {
    "Name": "component.farm.wind",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.farm.wind.js"
  },
  {
    "Name": "component.generator.abstract",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.generator.abstract.js"
  },
  {
    "Name": "component.load.impedance",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.load.impedance.js"
  },
  {
    "Name": "component.load.power",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.load.power.js"
  },
  {
    "Name": "controller.Abstract",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "Component",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.Abstract.js"
  },
  {
    "Name": "controller.broadcast_PI_AGC",
    "Type": "PowerSystemModel",
    "Model": "GlobalController",
    "Parent": "GlobalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.broadcast_PI_AGC.js"
  },
  {
    "Name": "component.GFM.DCsource.AbstractClass",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "LocalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.DCsource.AbstractClass.js"
  },
  {
    "Name": "component.GFM.ReferenceModel.AbstractClass",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "LocalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.ReferenceModel.AbstractClass.js"
  },
  {
    "Name": "component.GFM.controller.AbstractClass",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "LocalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.controller.AbstractClass.js"
  },
  {
    "Name": "controller.local_LQR",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "LocalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.local_LQR.js"
  },
  {
    "Name": "controller.local_LQR_retrofit",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "LocalController",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.local_LQR_retrofit.js"
  },
  {
    "Name": "tools.for_graph.map_forAnime1",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "tools.for_graph.map",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map_forAnime1.js"
  },
  {
    "Name": "tools.for_graph.map_forAnime2",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "tools.for_graph.map",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map_forAnime2.js"
  },
  {
    "Name": "tools.for_graph.map_forAnime3",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "tools.for_graph.map",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map_forAnime3.js"
  },
  {
    "Name": "tools.for_graph.map_forUI",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "tools.for_graph.map",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map_forUI.js"
  },
  {
    "Name": "tools.for_graph.map_polar",
    "Type": "auxiliary",
    "Model": "",
    "Parent": "tools.for_graph.map",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAsystem/tools.for_graph.map_polar.js"
  },
  {
    "Name": "component.GFM.DCsource.Delay1order_model",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.DCsource.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.DCsource.Delay1order_model.js"
  },
  {
    "Name": "component.GFM.DCsource.Vconstant",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.DCsource.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.DCsource.Vconstant.js"
  },
  {
    "Name": "component.GFM.droop",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.droop.js"
  },
  {
    "Name": "component.GFM.droop_DC1order",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.droop_DC1order.js"
  },
  {
    "Name": "component.GFM.droop_DCconst",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.droop_DCconst.js"
  },
  {
    "Name": "component.GFM.vsm1axis_DCconst",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.vsm1axis_DCconst.js"
  },
  {
    "Name": "component.GFM.vsm_DC1order",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.vsm_DC1order.js"
  },
  {
    "Name": "component.GFM.vsm_DCconst",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.GFM.Inverter",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.vsm_DCconst.js"
  },
  {
    "Name": "component.GFM.ReferenceModel.droop",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.ReferenceModel.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.ReferenceModel.droop.js"
  },
  {
    "Name": "component.GFM.ReferenceModel.vsm",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.ReferenceModel.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.ReferenceModel.vsm.js"
  },
  {
    "Name": "component.GFM.ReferenceModel.vsm1axis",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.ReferenceModel.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.ReferenceModel.vsm1axis.js"
  },
  {
    "Name": "component.GFM.controller.low_level_cascade",
    "Type": "PowerSystemModel",
    "Model": "LocalController",
    "Parent": "component.GFM.controller.AbstractClass",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.GFM.controller.low_level_cascade.js"
  },
  {
    "Name": "component.generator.classical",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.generator.abstract",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.generator.classical.js"
  },
  {
    "Name": "component.generator.one_axis",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.generator.abstract",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.generator.one_axis.js"
  },
  {
    "Name": "component.generator.park",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "component.generator.abstract",
    "Abstract": false,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/component.generator.park.js"
  },
  {
    "Name": "controller.AVR_DC1",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "controller.Abstract",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.AVR_DC1.js"
  },
  {
    "Name": "controller.PSS1",
    "Type": "PowerSystemModel",
    "Model": "Component",
    "Parent": "controller.Abstract",
    "Abstract": true,
    "Hidden": false,
    "Desc": "",
    "Role": "",
    "Constructor": "",
    "path": "/Users/taku/Library/CloudStorage/MATLAB-Drive/_GUILDA/Development_codeshare_ver2/_GUILDAdoc/database/GUILDAobject/controller.PSS1.js"
  }
];
