window.GUILDA_DOC_INDEX = {
  "schema": {
    "name": "GUILDA documentation class index",
    "version": 2,
    "classDocumentVersion": 2,
    "pathBase": "_GUILDAdoc",
    "modelCategories": [
      "PowerNetwork",
      "Bus",
      "Branch",
      "Component",
      "LocalController",
      "GlobalController"
    ],
    "coreClasses": [
      "PowerNetwork",
      "Bus",
      "Branch",
      "Component",
      "LocalController",
      "GlobalController"
    ],
    "tags": {
      "class": [
        "Summary",
        "Desc",
        "Role",
        "Constructor",
        "Notes",
        "SeeAlso",
        "Since",
        "Deprecated"
      ],
      "property": [
        "Summary",
        "Desc",
        "Role",
        "Type",
        "Size",
        "Unit",
        "Default",
        "Constraints",
        "Notes",
        "SeeAlso",
        "Since",
        "Deprecated"
      ],
      "method": [
        "Summary",
        "Desc",
        "Role",
        "Signatures",
        "Parameters",
        "Returns",
        "Examples",
        "Notes",
        "Throws",
        "SeeAlso",
        "Since",
        "Deprecated"
      ],
      "structured": [
        "Signatures",
        "Parameters",
        "Returns",
        "Examples",
        "SeeAlso"
      ]
    },
    "legacyAliases": {
      "Abst": "Summary",
      "varargin": "Parameters",
      "varargout": "Returns",
      "DetailsCode": "Notes"
    }
  },
  "classes": [
    {
      "Name": "LayerPackage",
      "Type": "auxiliary",
      "Model": "",
      "Parent": "handle",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "Abstract base class for layer hierarchy management in GUILDA.\nIt centralizes parent/children relationships, tag handling, and edit logging.",
      "Role": "auxiliary",
      "Constructor": "This class is abstract and should not be instantiated directly.\n\nLayerPackage のドキュメンテーション\ndoc LayerPackage",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 1,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/LayerPackage.js"
    },
    {
      "Name": "Branch",
      "Type": "PowerSystemModel",
      "Model": "Branch",
      "Parent": "PowerSystemModel",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "Abstract class representing a branch in the power system, such as a transmission line or transformer.\nIt defines the structure and parameters of a branch, including its connection to buses and cubicles.\nMain function\n- build admittance matrix\n- build OPF problem\n- build ode function",
      "Role": "Power System Model",
      "Constructor": "Branch(tag, struct_default, opt)\n\nBranch のドキュメンテーション\ndoc Branch",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 3,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/Branch.js"
    },
    {
      "Name": "Bus",
      "Type": "PowerSystemModel",
      "Model": "Bus",
      "Parent": "PowerSystemModel",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/Bus.js"
    },
    {
      "Name": "Component",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "PowerSystemModel",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 11,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/Component.js"
    },
    {
      "Name": "GlobalController",
      "Type": "PowerSystemModel",
      "Model": "GlobalController",
      "Parent": "PowerSystemModel",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 7,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/GlobalController.js"
    },
    {
      "Name": "LocalController",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "PowerSystemModel",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 10,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/LocalController.js"
    },
    {
      "Name": "PowerNetwork",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerSystemModel",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 22,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAsystem/PowerNetwork.js"
    },
    {
      "Name": "branch.T",
      "Type": "PowerSystemModel",
      "Model": "Branch",
      "Parent": "Branch",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/branch.T.js"
    },
    {
      "Name": "branch.pi",
      "Type": "PowerSystemModel",
      "Model": "Branch",
      "Parent": "Branch",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/branch.pi.js"
    },
    {
      "Name": "branch.pi_transformer",
      "Type": "PowerSystemModel",
      "Model": "Branch",
      "Parent": "Branch",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/branch.pi_transformer.js"
    },
    {
      "Name": "branch.two_winding_transformer",
      "Type": "PowerSystemModel",
      "Model": "Branch",
      "Parent": "Branch",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/branch.two_winding_transformer.js"
    },
    {
      "Name": "component.GFM.Inverter",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "Component",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 14,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.Inverter.js"
    },
    {
      "Name": "component.farm.solar",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "Component",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 6,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.farm.solar.js"
    },
    {
      "Name": "component.farm.wind",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "Component",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 6,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.farm.wind.js"
    },
    {
      "Name": "component.generator.abstract",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "Component",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 4,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.abstract.js"
    },
    {
      "Name": "component.load.abstract",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "Component",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.load.abstract.js"
    },
    {
      "Name": "controller.agc.broadcast_PI_AGC",
      "Type": "PowerSystemModel",
      "Model": "GlobalController",
      "Parent": "GlobalController",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 15,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.agc.broadcast_PI_AGC.js"
    },
    {
      "Name": "component.GFM.DCsource.AbstractClass",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.DCsource.AbstractClass.js"
    },
    {
      "Name": "component.GFM.ReferenceModel.AbstractClass",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 9,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.ReferenceModel.AbstractClass.js"
    },
    {
      "Name": "component.GFM.controller.AbstractClass",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.controller.AbstractClass.js"
    },
    {
      "Name": "controller.avr.base",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.avr.base.js"
    },
    {
      "Name": "controller.pss.base",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 7,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.pss.base.js"
    },
    {
      "Name": "controller.local_LQR",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 10,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.local_LQR.js"
    },
    {
      "Name": "controller.local_LQR_retrofit",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "LocalController",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.local_LQR_retrofit.js"
    },
    {
      "Name": "network.IEEE14bus",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "test code of ieee-14bus system\n%==================================================================================%%% \n%                          <<< IEEE 14-Bus System >>>                              %%%\n%==================================================================================%%%\n%                                                                                  %%%\n%   The IEEE 14-bus system is a standard test case for power system analysis.      %%%\n%  It represents a small part of the American Electric Power System and is         %%%\n%  widely used to test power flow, stability, and contingency analysis.            %%%\n%                                                                                  %%%\n%                       =<< System Overview >>=                                    %%%\n%                                                                                  %%%\n%   The model includes 14 buses, 5 generators, 11 loads, 16                        %%%\n%  transmission lines, and 2 transformers. Buses are classified as:                %%%\n%                                                                                  %%%\n%  ・Slack Bus (Bus 1)         : The reference bus with a fixed voltage and angle. %%%\n%  ・PV Buses  (Bus 2, 3, 6, 8): Have fixed voltage and real power.                %%%\n%  ・PQ Buses  (The rest)      : Have fixed real and reactive power loads.         %%%\n%                                                                                  %%%\n%==================================================================================%%%\n\n=<< IEEE 14-Bus System Diagram >>=\n\n\nLL             LL             \n|              |\n(13) ===========       ===== (14)\n|   |   |         | |\nLL        |   |   └---------┘ └------------┐\n|         |   |                            |\n(12) =====       |   |        LL      LL          |\n| |        |   |        |       |           |\n| └--------┘   | (11) =====   ===== (10)    |\n|              |       | |     | |          |\n└----------┐   |   ┌---┘ └-----┘ └-----┐    |\n|   |   |                   |    |   ┌-- LL\n|   |   |                   |    |   |\n=========== (6)       (9) ==============\n|   |   |                 |   |      | ┌-----------┐\nSC  |   LL               ///  |      | |           |\n~~~                       ~~~    ~~~~~ (7)     === (8)\n|                         |       |            |                                                                    \nSG               LL --┐ |                         |       |            SC\n|                     | |                     ============== (4)\n===== (1)              ======= (5)               |  |  |    |\n| |                    | | |                    |  |  |    LL\n| └--------------------┘ | └--------------------┘  |  |\n└----------┐  ┌----------┘                         |  |\n|  |  ┌---------------------------------┘  |\n|  |  |                                    |\n|  |  |                       ┌------------┘ \n========= (2)                  |          \n|  |  |                       |          \nSG LL |                       |\n└-------------------┐   |\n|   |\n|   |\n======= (3)\n|   |\nSC  LL\n\n\n< symbol >       < name >\n--, | :   Transmission Line\n~~~  :   Transformer\nSG   :   Synchronous Generator\nSC   :   Synchronous Compensator\nLL   :   Load\n===  :   Bus\n(.)  :   Bus Number\n///  :   Shunt (bus)\n\n====================================================================================\n<Model> IEEE14bus\n<Summary>\nBus       : 14\nBranch    : 20\nComponent : 17\n> SG     : 5\n> Load   : 12\n> Others : 0",
      "Role": "PowerNetwork COnstructor",
      "Constructor": "net = IEEE14bus()\n\nnetwork.IEEE14bus のドキュメンテーション\ndoc network.IEEE14bus",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "ok",
      "DocumentationWarnings": 0,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.IEEE14bus.js"
    },
    {
      "Name": "network.IEEE14bus_lossless",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "test code of ieee-14bus system\n%==================================================================================%%% \n%                          <<< IEEE 14-Bus System >>>                              %%%\n%==================================================================================%%%\n%                                                                                  %%%\n%   The IEEE 14-bus system is a standard test case for power system analysis.      %%%\n%  It represents a small part of the American Electric Power System and is         %%%\n%  widely used to test power flow, stability, and contingency analysis.            %%%\n%                                                                                  %%%\n%                       =<< System Overview >>=                                    %%%\n%                                                                                  %%%\n%   The model includes 14 buses, 5 generators, 11 loads, 16                        %%%\n%  transmission lines, and 2 transformers. Buses are classified as:                %%%\n%                                                                                  %%%\n%  ・Slack Bus (Bus 1)         : The reference bus with a fixed voltage and angle. %%%\n%  ・PV Buses  (Bus 2, 3, 6, 8): Have fixed voltage and real power.                %%%\n%  ・PQ Buses  (The rest)      : Have fixed real and reactive power loads.         %%%\n%                                                                                  %%%\n%==================================================================================%%%\n\n=<< IEEE 14-Bus System Diagram >>=\n\n\nLL             LL             \n|              |\n(13) ===========       ===== (14)\n|   |   |         | |\nLL        |   |   └---------┘ └------------┐\n|         |   |                            |\n(12) =====       |   |        LL      LL          |\n| |        |   |        |       |           |\n| └--------┘   | (11) =====   ===== (10)    |\n|              |       | |     | |          |\n└----------┐   |   ┌---┘ └-----┘ └-----┐    |\n|   |   |                   |    |   ┌-- LL\n|   |   |                   |    |   |\n=========== (6)       (9) ==============\n|   |   |                 |   |      | ┌-----------┐\nSC  |   LL               ///  |      | |           |\n~~~                       ~~~    ~~~~~ (7)     === (8)\n|                         |       |            |                                                                    \nSG               LL --┐ |                         |       |            SC\n|                     | |                     ============== (4)\n===== (1)              ======= (5)               |  |  |    |\n| |                    | | |                    |  |  |    LL\n| └--------------------┘ | └--------------------┘  |  |\n└----------┐  ┌----------┘                         |  |\n|  |  ┌---------------------------------┘  |\n|  |  |                                    |\n|  |  |                       ┌------------┘ \n========= (2)                  |          \n|  |  |                       |          \nSG LL |                       |\n└-------------------┐   |\n|   |\n|   |\n======= (3)\n|   |\nSC  LL\n\n\n< symbol >       < name >\n--, | :   Transmission Line\n~~~  :   Transformer\nSG   :   Synchronous Generator\nSC   :   Synchronous Compensator\nLL   :   Load\n===  :   Bus\n(.)  :   Bus Number\n///  :   Shunt (bus)\n\n====================================================================================\n<Model> IEEE14bus\n<Summary>\nBus       : 14\nBranch    : 20\nComponent : 17\n> SG     : 5\n> Load   : 12\n> Others : 0",
      "Role": "PowerNetwork COnstructor",
      "Constructor": "net = IEEE14bus()\n\nnetwork.IEEE14bus_lossless のドキュメンテーション\ndoc network.IEEE14bus_lossless",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "ok",
      "DocumentationWarnings": 0,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.IEEE14bus_lossless.js"
    },
    {
      "Name": "network.Ishizaki6Bus",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.Ishizaki6Bus.js"
    },
    {
      "Name": "network.TEST31bus",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "============================================================================================================================================================================================                                                                                  \n============================================================================================================================================================================================                                                                                  \n\n////////     ////        //////     //   //     ////          ////   ////      /////      //////      ////////      //\n//       //        //   //    //   //    //             // // // //     //   //     //   //     //            //\n/////       //   ===  //////     //   //     ////          //  ///  //     //   //     //    //    //////        //\n//       //        //   //    //   //         //        //       //     //   //     //   //     //            //\n////////      ////       //////      /////      /////         //       //      /////      //////      ////////      /////////\n\n============================================================================================================================================================================================ \n============================================================================================================================================================================================                                                                                  \n\n510 (8)   \n||\n┌---||---┐\n|   ||   |\nLL       |\n|\n| \n530 (9)   520 (10)  |  500 (11)          320 (12)      340 (13)           330 (14)          350 (15)      \n||         ||     └---||                  ||-------------||----------------||----------------||                   \n┌---||---------||---------||------------------||             ||                ||                ||                   \n|   ||         ||---┐     ||---┐          ┌---||---┐         ||---┐        ┌---||        ┌-------||---┐            100 (3)      \n|                   |          |          |        |              |        |             |            |               ||    \nLL                  LL         LL         LL       |              LL       LL            |            LL              ||-----SG\n| ┌---LL                              |                            ||    \n| |                                   |                            ||         \n310 (16) =======                                  |               110 (17)     ||    \n|                                     |                  ||        ||-----SG\n|                                     |         ┌--------||--------||    \n| ┌---LL                              |         |    ┌---||        ||         \n| |                                   |         |    |             ||    \n======= 300 (18)             360 (19)    |         |    LL            ||-----SG\n250 (20)          260 (7)          |   |                         ||        |         |                  ||    \n||               ||--------------┘   └-------------------------||--------┘         |                  ||         \n┌----||---------------||         370 (21)                           ||---┐              |     ┌------------||    \n|    ||---┐           ||            ||                                   |              |     |            ||-----SG\n|         |           ||------------||---┐                               LL             |     |            ||    \n|         LL          ||            ||   |                                              |     |            ||\n|                     ||---┐             LL                         1311 (1)            |     |       ┌----||--------------------┐\n|                          |                                         ||                 |     |       |    ||------┐             |\n|                          LL                                 ┌------||----SG           |     |       LL           |             |\n|                                                             |      ||                 |     |                    |         ========= 170 (30)\n|                                                             |                         |     |                    |             |  |\n|                                             130 (5) ============================================                 |             |  LL\n|                                                       |           |            |            |            ||------┘             |\n2412 (2)    240 (6)        |                                                       |           |            |            |            ||                    |\n||        ||          |                                                       |           |            |            |            ||                 ======= 180 (31)  \nSC----||--------||----------┘                                                       |           |            |            |            ||-----SG             |  \n||        ||                                                                  |           |            |            |            ||                    |  \n||----┐                                                             |           |            |            └------------||                    LL\n||    |                                                             |           |            |                         ||\n270 (22)     ||    LL   230 (23)   220 (24)    210 (25)   200 (26)    150 (27)   |           |            |                         ||-----SG\n||        ||          ||          ||          ||          ||          ||      |           |            |                         ||\n┌----||--------||----------||----------||----------||----------||----------||------┘           |            |                    ┌----||\n|    ||        ||          ||---┐      ||---┐      ||---┐      ||---┐      ||---┐              |            |                    |    ||\nLL                              |           |           |           |           |   140 (28) =====        ===== 160 (29)         |    ||-----SG\nLL          LL          LL          LL          LL             |            |                    LL   ||\n|            |                         ||\nLL           LL                        ||\n< symbol >         < name >                                                                                                                    ||-----SG\n--, |   :   Transmission Line                                                                                                               ||\n||\n>>                                                                                                                                        120 (4)\n>>     :   Transformer      \n>>\n\nSG     :   Synchronous Generator\nSC     :   Synchronous Compensator\nLL     :   Load\n===, ||  :   Bus\n(.)    :   Bus Number",
      "Role": "PowerNetwork COnstructor",
      "Constructor": "net = TEST31bus()\n\nnetwork.TEST31bus のドキュメンテーション\ndoc network.TEST31bus",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "ok",
      "DocumentationWarnings": 0,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.TEST31bus.js"
    },
    {
      "Name": "network.Txt3Bus",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.Txt3Bus.js"
    },
    {
      "Name": "network.Tutorial3bus",
      "Type": "PowerSystemModel",
      "Model": "PowerNetwork",
      "Parent": "PowerNetwork",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/network.Tutorial3bus.js"
    },
    {
      "Name": "component.GFM.DCsource.Delay1order_model",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.DCsource.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.DCsource.Delay1order_model.js"
    },
    {
      "Name": "component.GFM.DCsource.Vconstant",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.DCsource.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.DCsource.Vconstant.js"
    },
    {
      "Name": "component.GFM.droop",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.droop.js"
    },
    {
      "Name": "component.GFM.droop_DC1order",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.droop_DC1order.js"
    },
    {
      "Name": "component.GFM.droop_DCconst",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.droop_DCconst.js"
    },
    {
      "Name": "component.GFM.vsm1axis_DCconst",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.vsm1axis_DCconst.js"
    },
    {
      "Name": "component.GFM.vsm_DC1order",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.vsm_DC1order.js"
    },
    {
      "Name": "component.GFM.vsm_DCconst",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.GFM.Inverter",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 2,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.vsm_DCconst.js"
    },
    {
      "Name": "component.GFM.ReferenceModel.droop",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.ReferenceModel.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.ReferenceModel.droop.js"
    },
    {
      "Name": "component.GFM.ReferenceModel.vsm",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.ReferenceModel.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.ReferenceModel.vsm.js"
    },
    {
      "Name": "component.GFM.ReferenceModel.vsm1axis",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.ReferenceModel.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.ReferenceModel.vsm1axis.js"
    },
    {
      "Name": "component.GFM.controller.low_level_cascade",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "component.GFM.controller.AbstractClass",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.GFM.controller.low_level_cascade.js"
    },
    {
      "Name": "component.generator.classical",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.generator.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 9,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.classical.js"
    },
    {
      "Name": "component.generator.droop",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.generator.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.droop.js"
    },
    {
      "Name": "component.generator.one_axis",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.generator.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.one_axis.js"
    },
    {
      "Name": "component.generator.park",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.generator.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 9,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.park.js"
    },
    {
      "Name": "component.generator.two_axis",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.generator.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 9,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.generator.two_axis.js"
    },
    {
      "Name": "component.ConstSource.power",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.load.abstract",
      "Abstract": true,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 6,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.ConstSource.power.js"
    },
    {
      "Name": "component.load.impedance",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.load.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 7,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.load.impedance.js"
    },
    {
      "Name": "component.load.power",
      "Type": "PowerSystemModel",
      "Model": "Component",
      "Parent": "component.load.abstract",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/component.load.power.js"
    },
    {
      "Name": "controller.avr.AVR_DC1",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "controller.avr.base",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.avr.AVR_DC1.js"
    },
    {
      "Name": "controller.avr.AVR_ST1",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "controller.avr.base",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 8,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.avr.AVR_ST1.js"
    },
    {
      "Name": "controller.pss.PSS1",
      "Type": "PowerSystemModel",
      "Model": "LocalController",
      "Parent": "controller.pss.base",
      "Abstract": false,
      "Hidden": false,
      "Summary": "",
      "Desc": "",
      "Role": "",
      "Constructor": "",
      "Notes": "",
      "SeeAlso": [],
      "Since": "",
      "Deprecated": "",
      "DocumentationStatus": "warning",
      "DocumentationWarnings": 7,
      "DocumentationErrors": 0,
      "path": "./database/GUILDAobject/controller.pss.PSS1.js"
    }
  ],
  "validation": {
    "warningCount": 328,
    "errorCount": 0,
    "classes": [
      {
        "ClassName": "LayerPackage",
        "Warnings": [
          "LayerPackage.struct: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "Branch",
        "Warnings": [
          "Branch.get_admittance_matrix: public method has no Summary or Desc.",
          "Branch.reset_odeset: public method has no Summary or Desc.",
          "Branch.build_opf_problem: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "Bus",
        "Warnings": [
          "Bus: class has no Summary or Desc.",
          "Bus.get_sys: public method has no Summary or Desc.",
          "Bus.reset_odeset: public method has no Summary or Desc.",
          "Bus.build_opf_problem: public method has no Summary or Desc.",
          "Bus.get_pf_set: public method has no Summary or Desc.",
          "Bus.replace_component: public method has no Summary or Desc.",
          "Bus.add_component: public method has no Summary or Desc.",
          "Bus.remove_component: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "Component",
        "Warnings": [
          "Component: class has no Summary or Desc.",
          "Component.set_odefcn: public method has no Summary or Desc.",
          "Component.get_equilibrium: public method has no Summary or Desc.",
          "Component.getJacobian: public method has no Summary or Desc.",
          "Component.get_dx_algebraic: public method has no Summary or Desc.",
          "Component.get_sys: public method has no Summary or Desc.",
          "Component.reset_odeset: public method has no Summary or Desc.",
          "Component.build_opf_problem: public method has no Summary or Desc.",
          "Component.remove_local_controller: public method has no Summary or Desc.",
          "Component.add_local_controller: public method has no Summary or Desc.",
          "Component.validate: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "GlobalController",
        "Warnings": [
          "GlobalController: class has no Summary or Desc.",
          "GlobalController.set_odefcn: public method has no Summary or Desc.",
          "GlobalController.fcn_Mass: public method has no Summary or Desc.",
          "GlobalController.fcn_y: public method has no Summary or Desc.",
          "GlobalController.fcn_dx: public method has no Summary or Desc.",
          "GlobalController.get_sys: public method has no Summary or Desc.",
          "GlobalController.GlobalController: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "LocalController",
        "Warnings": [
          "LocalController: class has no Summary or Desc.",
          "LocalController.set_odefcn: public method has no Summary or Desc.",
          "LocalController.fcn_Mass: public method has no Summary or Desc.",
          "LocalController.fcn_y: public method has no Summary or Desc.",
          "LocalController.fcn_dx: public method has no Summary or Desc.",
          "LocalController.LocalController: public method has no Summary or Desc.",
          "LocalController.get_sys: public method has no Summary or Desc.",
          "LocalController.get_dx_algebraic: public method has no Summary or Desc.",
          "LocalController.set_parent: public method has no Summary or Desc.",
          "LocalController.add_local_controller: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "PowerNetwork",
        "Warnings": [
          "PowerNetwork: class has no Summary or Desc.",
          "PowerNetwork.PowerNetwork: public method has no Summary or Desc.",
          "PowerNetwork.draw_diagram: public method has no Summary or Desc.",
          "PowerNetwork.info: public method has no Summary or Desc.",
          "PowerNetwork.reset_odeset: public method has no Summary or Desc.",
          "PowerNetwork.simulate: public method has no Summary or Desc.",
          "PowerNetwork.get_admittance_matrix: public method has no Summary or Desc.",
          "PowerNetwork.get_sys: public method has no Summary or Desc.",
          "PowerNetwork.disp_pf_set: public method has no Summary or Desc.",
          "PowerNetwork.calculate_powerflow: public method has no Summary or Desc.",
          "PowerNetwork.build_opf_problem: public method has no Summary or Desc.",
          "PowerNetwork.optimize_powerflow: public method has no Summary or Desc.",
          "PowerNetwork.initialize: public method has no Summary or Desc.",
          "PowerNetwork.set_pf_set: public method has no Summary or Desc.",
          "PowerNetwork.remove_global_controller: public method has no Summary or Desc.",
          "PowerNetwork.remove_branch: public method has no Summary or Desc.",
          "PowerNetwork.remove_bus: public method has no Summary or Desc.",
          "PowerNetwork.add_global_controller: public method has no Summary or Desc.",
          "PowerNetwork.add_branch: public method has no Summary or Desc.",
          "PowerNetwork.add_bus: public method has no Summary or Desc.",
          "PowerNetwork.draw_spring_model: public method has no Summary or Desc.",
          "PowerNetwork.set_equilibrium: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "branch.T",
        "Warnings": [
          "branch.T: class has no Summary or Desc.",
          "branch.T.get_admittance_matrix: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "branch.pi",
        "Warnings": [
          "branch.pi: class has no Summary or Desc.",
          "branch.pi.get_admittance_matrix: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "branch.pi_transformer",
        "Warnings": [
          "branch.pi_transformer: class has no Summary or Desc.",
          "branch.pi_transformer.get_admittance_matrix: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "branch.two_winding_transformer",
        "Warnings": [
          "branch.two_winding_transformer: class has no Summary or Desc.",
          "branch.two_winding_transformer.get_admittance_matrix: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.Inverter",
        "Warnings": [
          "component.GFM.Inverter: class has no Summary or Desc.",
          "component.GFM.Inverter.get_equilibrium: public method has no Summary or Desc.",
          "component.GFM.Inverter.get_dx_constraint: public method has no Summary or Desc.",
          "component.GFM.Inverter.set_dc_source: public method has no Summary or Desc.",
          "component.GFM.Inverter.set_reference_model: public method has no Summary or Desc.",
          "component.GFM.Inverter.set_vsc_controller: public method has no Summary or Desc.",
          "component.GFM.Inverter.calc_base: public method has no Summary or Desc.",
          "component.GFM.Inverter.set_Vbase: public method has no Summary or Desc.",
          "component.GFM.Inverter.set_Sbase: public method has no Summary or Desc.",
          "component.GFM.Inverter.naming_port: public method has no Summary or Desc.",
          "component.GFM.Inverter.naming_state: public method has no Summary or Desc.",
          "component.GFM.Inverter.get_nu: public method has no Summary or Desc.",
          "component.GFM.Inverter.get_nx: public method has no Summary or Desc.",
          "component.GFM.Inverter.Inverter: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.farm.solar",
        "Warnings": [
          "component.farm.solar: class has no Summary or Desc.",
          "component.farm.solar.get_equilibrium: public method has no Summary or Desc.",
          "component.farm.solar.get_nx: public method has no Summary or Desc.",
          "component.farm.solar.get_nu: public method has no Summary or Desc.",
          "component.farm.solar.get_dx_constraint: public method has no Summary or Desc.",
          "component.farm.solar.solar: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.farm.wind",
        "Warnings": [
          "component.farm.wind: class has no Summary or Desc.",
          "component.farm.wind.get_dx_constraint: public method has no Summary or Desc.",
          "component.farm.wind.get_equilibrium: public method has no Summary or Desc.",
          "component.farm.wind.get_nx: public method has no Summary or Desc.",
          "component.farm.wind.get_nu: public method has no Summary or Desc.",
          "component.farm.wind.wind: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.abstract",
        "Warnings": [
          "component.generator.abstract: class has no Summary or Desc.",
          "component.generator.abstract.set_pss: public method has no Summary or Desc.",
          "component.generator.abstract.set_avr: public method has no Summary or Desc.",
          "component.generator.abstract.set_governor: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.load.abstract",
        "Warnings": [
          "component.load.abstract: class has no Summary or Desc.",
          "component.load.abstract.abstract: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.agc.broadcast_PI_AGC",
        "Warnings": [
          "controller.agc.broadcast_PI_AGC: class has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiDyu: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiDyi: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiDyv: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiCyx: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiBxu: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiBxi: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiBxv: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.getJacobiAxx: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.fcn_Mass: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.fcn_y: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.fcn_dx: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.get_equilibrium: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.set_odefcn: public method has no Summary or Desc.",
          "controller.agc.broadcast_PI_AGC.broadcast_PI_AGC: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.DCsource.AbstractClass",
        "Warnings": [
          "component.GFM.DCsource.AbstractClass: class has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.set_equilibrium: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.get_dx_vdc: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.get_nu: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.get_nx: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.naming_port: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.naming_state: public method has no Summary or Desc.",
          "component.GFM.DCsource.AbstractClass.AbstractClass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.ReferenceModel.AbstractClass",
        "Warnings": [
          "component.GFM.ReferenceModel.AbstractClass: class has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.get_Vterminal: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.get_equilibrium: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.get_dx_constraint: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.get_nu: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.get_nx: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.naming_port: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.naming_state: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.AbstractClass.AbstractClass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.controller.AbstractClass",
        "Warnings": [
          "component.GFM.controller.AbstractClass: class has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.set_equilibrium: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.get_dx_mdq: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.get_nu: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.get_nx: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.naming_port: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.naming_state: public method has no Summary or Desc.",
          "component.GFM.controller.AbstractClass.AbstractClass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.avr.base",
        "Warnings": [
          "controller.avr.base: class has no Summary or Desc.",
          "controller.avr.base.set_PSS: public method has no Summary or Desc.",
          "controller.avr.base.get_equilibrium: public method has no Summary or Desc.",
          "controller.avr.base.set_odefcn: public method has no Summary or Desc.",
          "controller.avr.base.base: public method has no Summary or Desc.",
          "controller.avr.base.fcn_y: public method has no Summary or Desc.",
          "controller.avr.base.fcn_dx: public method has no Summary or Desc.",
          "controller.avr.base.fcn_Mass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.pss.base",
        "Warnings": [
          "controller.pss.base: class has no Summary or Desc.",
          "controller.pss.base.get_equilibrium: public method has no Summary or Desc.",
          "controller.pss.base.set_odefcn: public method has no Summary or Desc.",
          "controller.pss.base.base: public method has no Summary or Desc.",
          "controller.pss.base.fcn_Mass: public method has no Summary or Desc.",
          "controller.pss.base.fcn_y: public method has no Summary or Desc.",
          "controller.pss.base.fcn_dx: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.local_LQR",
        "Warnings": [
          "controller.local_LQR: class has no Summary or Desc.",
          "controller.local_LQR.refresh_utab: public method has no Summary or Desc.",
          "controller.local_LQR.refresh_xtab: public method has no Summary or Desc.",
          "controller.local_LQR.set_parameter: public method has no Summary or Desc.",
          "controller.local_LQR.set_index: public method has no Summary or Desc.",
          "controller.local_LQR.get_linear_matrix: public method has no Summary or Desc.",
          "controller.local_LQR.get_dx_u: public method has no Summary or Desc.",
          "controller.local_LQR.initialize: public method has no Summary or Desc.",
          "controller.local_LQR.get_nx: public method has no Summary or Desc.",
          "controller.local_LQR.local_LQR: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.local_LQR_retrofit",
        "Warnings": [
          "controller.local_LQR_retrofit: class has no Summary or Desc.",
          "controller.local_LQR_retrofit.get_linear_matrix: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.get_dx_u_linear: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.get_dx_u: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.initialize: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.get_nu: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.get_nx: public method has no Summary or Desc.",
          "controller.local_LQR_retrofit.local_LQR_retrofit: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "network.IEEE14bus",
        "Warnings": [],
        "Errors": []
      },
      {
        "ClassName": "network.IEEE14bus_lossless",
        "Warnings": [],
        "Errors": []
      },
      {
        "ClassName": "network.Ishizaki6Bus",
        "Warnings": [
          "network.Ishizaki6Bus: class has no Summary or Desc.",
          "network.Ishizaki6Bus.Ishizaki6Bus: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "network.TEST31bus",
        "Warnings": [],
        "Errors": []
      },
      {
        "ClassName": "network.Txt3Bus",
        "Warnings": [
          "network.Txt3Bus: class has no Summary or Desc.",
          "network.Txt3Bus.Txt3Bus: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "network.Tutorial3bus",
        "Warnings": [
          "network.Tutorial3bus: class has no Summary or Desc.",
          "network.Tutorial3bus.Tutorial3bus: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.DCsource.Delay1order_model",
        "Warnings": [
          "component.GFM.DCsource.Delay1order_model: class has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.set_equilibrium: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.get_dx_vdc: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.naming_port: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.naming_state: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.get_nu: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.get_nx: public method has no Summary or Desc.",
          "component.GFM.DCsource.Delay1order_model.Delay1order_model: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.DCsource.Vconstant",
        "Warnings": [
          "component.GFM.DCsource.Vconstant: class has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.set_equilibrium: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.get_dx_vdc: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.naming_port: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.naming_state: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.get_nu: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.get_nx: public method has no Summary or Desc.",
          "component.GFM.DCsource.Vconstant.Vconstant: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.droop",
        "Warnings": [
          "component.GFM.droop: class has no Summary or Desc.",
          "component.GFM.droop.droop: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.droop_DC1order",
        "Warnings": [
          "component.GFM.droop_DC1order: class has no Summary or Desc.",
          "component.GFM.droop_DC1order.droop_DC1order: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.droop_DCconst",
        "Warnings": [
          "component.GFM.droop_DCconst: class has no Summary or Desc.",
          "component.GFM.droop_DCconst.droop_DCconst: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.vsm1axis_DCconst",
        "Warnings": [
          "component.GFM.vsm1axis_DCconst: class has no Summary or Desc.",
          "component.GFM.vsm1axis_DCconst.vsm1axis_DCconst: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.vsm_DC1order",
        "Warnings": [
          "component.GFM.vsm_DC1order: class has no Summary or Desc.",
          "component.GFM.vsm_DC1order.vsm_DC1order: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.vsm_DCconst",
        "Warnings": [
          "component.GFM.vsm_DCconst: class has no Summary or Desc.",
          "component.GFM.vsm_DCconst.vsm_DCconst: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.ReferenceModel.droop",
        "Warnings": [
          "component.GFM.ReferenceModel.droop: class has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.get_equilibrium: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.get_Vterminal: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.get_dx_constraint: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.naming_state: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.get_nu: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.get_nx: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.droop.droop: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.ReferenceModel.vsm",
        "Warnings": [
          "component.GFM.ReferenceModel.vsm: class has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.get_equilibrium: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.get_Vterminal: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.get_dx_constraint: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.naming_state: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.get_nu: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.get_nx: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm.vsm: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.ReferenceModel.vsm1axis",
        "Warnings": [
          "component.GFM.ReferenceModel.vsm1axis: class has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.get_equilibrium: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.get_Vterminal: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.get_dx_constraint: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.get_nu: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.get_nx: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.naming_state: public method has no Summary or Desc.",
          "component.GFM.ReferenceModel.vsm1axis.vsm1axis: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.GFM.controller.low_level_cascade",
        "Warnings": [
          "component.GFM.controller.low_level_cascade: class has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.set_equilibrium: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.get_dx_mdq: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.naming_port: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.naming_state: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.get_nu: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.get_nx: public method has no Summary or Desc.",
          "component.GFM.controller.low_level_cascade.low_level_cascade: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.classical",
        "Warnings": [
          "component.generator.classical: class has no Summary or Desc.",
          "component.generator.classical.get_equilibrium: public method has no Summary or Desc.",
          "component.generator.classical.set_odefcn: public method has no Summary or Desc.",
          "component.generator.classical.fcn_Mass: public method has no Summary or Desc.",
          "component.generator.classical.fcn_Y: public method has no Summary or Desc.",
          "component.generator.classical.fcn_I: public method has no Summary or Desc.",
          "component.generator.classical.fcn_dx: public method has no Summary or Desc.",
          "component.generator.classical.getCompPQ: public method has no Summary or Desc.",
          "component.generator.classical.classical: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.droop",
        "Warnings": [
          "component.generator.droop: class has no Summary or Desc.",
          "component.generator.droop.fcn_Mass: public method has no Summary or Desc.",
          "component.generator.droop.fcn_Y: public method has no Summary or Desc.",
          "component.generator.droop.fcn_I: public method has no Summary or Desc.",
          "component.generator.droop.fcn_dx: public method has no Summary or Desc.",
          "component.generator.droop.get_equilibrium: public method has no Summary or Desc.",
          "component.generator.droop.set_odefcn: public method has no Summary or Desc.",
          "component.generator.droop.droop: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.one_axis",
        "Warnings": [
          "component.generator.one_axis: class has no Summary or Desc.",
          "component.generator.one_axis.set_odefcn: public method has no Summary or Desc.",
          "component.generator.one_axis.get_equilibrium: public method has no Summary or Desc.",
          "component.generator.one_axis.fcn_Mass: public method has no Summary or Desc.",
          "component.generator.one_axis.fcn_Y: public method has no Summary or Desc.",
          "component.generator.one_axis.fcn_I: public method has no Summary or Desc.",
          "component.generator.one_axis.fcn_dx: public method has no Summary or Desc.",
          "component.generator.one_axis.one_axis: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.park",
        "Warnings": [
          "component.generator.park: class has no Summary or Desc.",
          "component.generator.park.set_odefcn: public method has no Summary or Desc.",
          "component.generator.park.getCompPQ: public method has no Summary or Desc.",
          "component.generator.park.get_equilibrium: public method has no Summary or Desc.",
          "component.generator.park.fcn_Mass: public method has no Summary or Desc.",
          "component.generator.park.fcn_Y: public method has no Summary or Desc.",
          "component.generator.park.fcn_I: public method has no Summary or Desc.",
          "component.generator.park.fcn_dx: public method has no Summary or Desc.",
          "component.generator.park.park: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.generator.two_axis",
        "Warnings": [
          "component.generator.two_axis: class has no Summary or Desc.",
          "component.generator.two_axis.set_odefcn: public method has no Summary or Desc.",
          "component.generator.two_axis.getCompPQ: public method has no Summary or Desc.",
          "component.generator.two_axis.get_equilibrium: public method has no Summary or Desc.",
          "component.generator.two_axis.fcn_Mass: public method has no Summary or Desc.",
          "component.generator.two_axis.fcn_Y: public method has no Summary or Desc.",
          "component.generator.two_axis.fcn_I: public method has no Summary or Desc.",
          "component.generator.two_axis.fcn_dx: public method has no Summary or Desc.",
          "component.generator.two_axis.two_axis: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.ConstSource.power",
        "Warnings": [
          "component.ConstSource.power: class has no Summary or Desc.",
          "component.ConstSource.power.get_linear_matrix: public method has no Summary or Desc.",
          "component.ConstSource.power.naming_port: public method has no Summary or Desc.",
          "component.ConstSource.power.get_dx_constraint: public method has no Summary or Desc.",
          "component.ConstSource.power.get_equilibrium: public method has no Summary or Desc.",
          "component.ConstSource.power.power: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.load.impedance",
        "Warnings": [
          "component.load.impedance: class has no Summary or Desc.",
          "component.load.impedance.set_odefcn: public method has no Summary or Desc.",
          "component.load.impedance.get_equilibrium: public method has no Summary or Desc.",
          "component.load.impedance.fcn_Mass: public method has no Summary or Desc.",
          "component.load.impedance.fcn_Y: public method has no Summary or Desc.",
          "component.load.impedance.fcn_I: public method has no Summary or Desc.",
          "component.load.impedance.fcn_dx: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "component.load.power",
        "Warnings": [
          "component.load.power: class has no Summary or Desc.",
          "component.load.power.set_odefcn: public method has no Summary or Desc.",
          "component.load.power.get_equilibrium: public method has no Summary or Desc.",
          "component.load.power.fcn_Mass: public method has no Summary or Desc.",
          "component.load.power.fcn_Y: public method has no Summary or Desc.",
          "component.load.power.fcn_I: public method has no Summary or Desc.",
          "component.load.power.fcn_dx: public method has no Summary or Desc.",
          "component.load.power.getCompPQ: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.avr.AVR_DC1",
        "Warnings": [
          "controller.avr.AVR_DC1: class has no Summary or Desc.",
          "controller.avr.AVR_DC1.set_PSS: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.get_equilibrium: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.set_odefcn: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.AVR_DC1: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.fcn_y: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.fcn_dx: public method has no Summary or Desc.",
          "controller.avr.AVR_DC1.fcn_Mass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.avr.AVR_ST1",
        "Warnings": [
          "controller.avr.AVR_ST1: class has no Summary or Desc.",
          "controller.avr.AVR_ST1.set_PSS: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.get_equilibrium: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.set_odefcn: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.AVR_ST1: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.fcn_y: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.fcn_dx: public method has no Summary or Desc.",
          "controller.avr.AVR_ST1.fcn_Mass: public method has no Summary or Desc."
        ],
        "Errors": []
      },
      {
        "ClassName": "controller.pss.PSS1",
        "Warnings": [
          "controller.pss.PSS1: class has no Summary or Desc.",
          "controller.pss.PSS1.get_equilibrium: public method has no Summary or Desc.",
          "controller.pss.PSS1.set_odefcn: public method has no Summary or Desc.",
          "controller.pss.PSS1.PSS1: public method has no Summary or Desc.",
          "controller.pss.PSS1.fcn_Mass: public method has no Summary or Desc.",
          "controller.pss.PSS1.fcn_y: public method has no Summary or Desc.",
          "controller.pss.PSS1.fcn_dx: public method has no Summary or Desc."
        ],
        "Errors": []
      }
    ]
  }
};
window.classListData = window.GUILDA_DOC_INDEX.classes;
const class_list = window.classListData;
