function h = draw_sphere(ax, x0, y0, z0, radius, color)
[xs, ys, zs] = sphere(14);
h = surf(ax, ...
    x0 + radius*xs, ...
    y0 + radius*ys, ...
    z0 + radius*zs, ...
    'FaceColor', color, ...
    'EdgeColor', 'none', ...
    'AmbientStrength', 0.20, ...
    'DiffuseStrength', 0.68, ...
    'SpecularStrength', 0.92, ...
    'SpecularExponent', 36, ...
    'BackFaceLighting', 'reverselit', ...
    'HandleVisibility', 'off');
end
