function h = not_draw()

    h = patch(        'Vertices', ones(4,2)*1e-5, ...
                         'Faces', ones(4,2), ...
                     'FaceColor', [1,1,1], ...
                     'EdgeColor', 'none', ...
               'AmbientStrength', 0.20, ...
               'DiffuseStrength', 0.70, ...
              'SpecularStrength', 0.92, ...
              'SpecularExponent', 34, ...
              'BackFaceLighting', 'reverselit', ...
              'HandleVisibility', 'off');
end
