function val = check_CostFunction(obj,func)
    try
        val = func(obj,0,[1;0],[1.01,0.01]);
    catch
        error(['The function handle seems to be in the wrong format.',newline,...
               'It must be in the following format',newline,...
               'func = @(obj,t,Vfrom,Vto) ~',newline,...
               '・obj : own class object',newline,...
               '・t = time(scalar)',newline,...
               '・Vfrom = [real(V);imag(V)] Bus voltage specified by obj.from',newline,...
               '・Vto   = [real(V);imag(V)] Bus voltage specified by obj.to',newline])
    end
end